apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: centmatch
  namespace: argocd
  labels:
    app.kubernetes.io/name: centmatch
    app.kubernetes.io/part-of: centmatch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Arceoavs/papsolver.git
    targetRevision: master
    path: kubernetes/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: centmatch
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
