apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: frontend-ingress
  namespace: papsolvue
spec:
  tls:
    - hosts:
        - papsolvue.awesomium.de
      secretName: wildcard
  rules:
    - host: papsolvue.awesomium.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
